drop table ADMINCERT cascade constraint ;
drop table SYSTEMCERT cascade constraint ;
drop table SPAREKEY cascade constraint ;
drop table TASKSCHEDULE cascade constraint ;
drop table OPTAPPLY cascade constraint ;
drop table ISSUERCERT cascade constraint ;
drop table ICCERT cascade constraint ;
drop table ARCHICCERT cascade constraint ;
drop table OPERATIONLOG cascade constraint ;
drop table OPERATIONLOGARC cascade constraint ;
drop table CONSOLEOPTLOG cascade constraint ;
drop SEQUENCE CONSOLEOPTLOG_AUTOID;
drop sequence LOG_AUTOID;