CREATE TABLE ADMINCERT (
   CERTSN               VARCHAR2(40)          NOT NULL,
   SUBJECTUPPERCASE     VARCHAR2(512)         NOT NULL,
   SUBJECT              VARCHAR2(512)         NOT NULL,
   COMMONNAME           VARCHAR2(128),
   NOTBEFORE            NUMBER(19)            NOT NULL,
   NOTAFTER             NUMBER(19)            NOT NULL,   
   ADMINSTATUS          VARCHAR2(12)          NOT NULL,
   ROLE					VARCHAR2(255)		  NOT NULL,
   SIGN_SERVER          VARCHAR2(256),
   CONSTRAINT PK_CERT PRIMARY KEY (CERTSN)
);
CREATE TABLE SYSTEMCERT (
   CERTSN               VARCHAR2(40)          NOT NULL,
   SUBJECT              VARCHAR2(512)         NOT NULL,
   NOTBEFORE            NUMBER(19),
   NOTAFTER             NUMBER(19),
   CERTTYPE             VARCHAR2(30)          NOT NULL,
   CERTSTATUS           VARCHAR2(12)          NOT NULL,
   DEVICE_ID            VARCHAR2(20),
   CERTENTITY           BLOB,
   CREATETIME           NUMBER(19),
   REMARK               VARCHAR2(256),
   SIGN_SERVER          VARCHAR2(256),
   CONSTRAINT PK_SYSTEMCERT PRIMARY KEY  (CERTSN)
);
CREATE TABLE SPAREKEY (
   ID                   VARCHAR2(40)          NOT NULL,
   KEYALG               VARCHAR2(15)          NOT NULL,
   KEYSIZE              NUMBER(6)             NOT NULL,
   GENTIME              NUMBER(19)            NOT NULL,
   PUBKEY               VARCHAR2(500)		  NOT NULL,
   PRIKEY               VARCHAR2(2001)        NOT NULL,
   SIGN_SERVER          VARCHAR2(256),
   CONSTRAINT PK_SPAREKEY PRIMARY KEY  (ID)
);
CREATE TABLE TASKSCHEDULE (
   ID                   VARCHAR2(40)          NOT NULL,
   KEYALG               VARCHAR2(15)          NOT NULL,
   KEYSIZE              NUMBER(6)             NOT NULL,
   STARTTIME            VARCHAR2(10)          NOT NULL,
   ENDTIME              VARCHAR2(10)          NOT NULL,
   MAXCNT               NUMBER(19),
   SIGN_SERVER          VARCHAR2(256),
   CONSTRAINT PK_TASKSCHEDULE PRIMARY KEY  (ID)
);
CREATE TABLE OPTAPPLY (
   REQSN                VARCHAR2(40)            NOT NULL,
   OPERATORSN           VARCHAR2(40)          	NOT NULL,
   OPERATORSUBJECTUPPERCASE VARCHAR2(512)       NOT NULL,
   OPERATORSUBJECT      VARCHAR2(512)         	NOT NULL,
   APPLYOBJECT			VARCHAR2(40)			NOT NULL,
   APPLYTYPE			VARCHAR2(50)			NOT NULL,
   APPLYTIME			NUMBER(19)				NOT NULL,
   APPLYSTATUS			VARCHAR2(20)			NOT NULL,
   REMARK				VARCHAR2(256),
   SIGN_SERVER			VARCHAR2(256),
   CONSTRAINT PK_OPTAPPLY PRIMARY KEY  (REQSN)
);
CREATE TABLE ISSUERCERT (
   ISSUERCERTID			VARCHAR2(20)			NOT NULL,
   RECORDID				VARCHAR2(20)			NOT NULL,
   CERTSN	            VARCHAR2(40),
   SERVICEID            VARCHAR2(20)          	NOT NULL,
   ISSUERBIN			VARCHAR2(20)         	NOT NULL,
   NOTAFTER			    NUMBER(19)		        NOT NULL,
   CERTSTATUS			VARCHAR2(20)		    NOT NULL,
   DEVICETYPE			VARCHAR2(20)		    NOT NULL,
   DEVICEID				VARCHAR2(20),
   KEYALG				VARCHAR2(15),
   KEYSIZE				NUMBER(6),
   PUBKEY				VARCHAR2(500),
   PRIKEY				VARCHAR2(2001),
   ISSUERENTITY			BLOB,
   ROOTPUBKEYID			VARCHAR2(20),
   ROOTCAENTITY			BLOB,
   SIGN_SERVER			VARCHAR2(256),
   CONSTRAINT PK_ISSUERCERT PRIMARY KEY  (ISSUERCERTID)
);
CREATE TABLE ICCERT (
   ICCERTID	            VARCHAR2(40)            NOT NULL,
   CERTSN	            VARCHAR2(40)            NOT NULL,
   ICCPAN				VARCHAR2(20)         	NOT NULL,
   NOTAFTER			    NUMBER(19)	         	NOT NULL,
   KEYALG				VARCHAR2(15)			NOT NULL,
   KEYSIZE				NUMBER(6)				NOT NULL,
   PUBKEY               VARCHAR2(500)        	NOT NULL,
   PRIKEY               VARCHAR2(2001)        	NOT NULL,   
   ICCENTITY			BLOB					NOT NULL,
   ISSUERBIN			VARCHAR2(20)			NOT NULL,
   CREATETIME			NUMBER(19)				NOT NULL,
   SIGN_SERVER			VARCHAR2(256),
   CONSTRAINT PK_ICCERT PRIMARY KEY  (ICCERTID)
);
CREATE TABLE ARCHICCERT (
   ICCERTID	            VARCHAR2(40)            NOT NULL,
   CERTSN	            VARCHAR2(40)            NOT NULL,
   ICCPAN				VARCHAR2(20)         	NOT NULL,
   NOTAFTER			    NUMBER(19)		        NOT NULL,
   KEYALG				VARCHAR2(15)			NOT NULL,
   KEYSIZE				NUMBER(6)				NOT NULL,
   PUBKEY               VARCHAR2(500)        	NOT NULL,
   PRIKEY               VARCHAR2(2001)        	NOT NULL,   
   ICCENTITY			BLOB					NOT NULL,
   ISSUERBIN			VARCHAR2(20)			NOT NULL,
   CREATETIME			NUMBER(19)				NOT NULL,
   ARCHIVETIME			NUMBER(19)				NOT NULL,
   SIGN_SERVER			VARCHAR2(256),
   CONSTRAINT PK_ARCHICCERT PRIMARY KEY  (ICCERTID)
);
CREATE TABLE OPERATIONLOG (
   ID                   NUMBER               	NOT NULL,
   OPERATORSN           VARCHAR2(40),
   OPERATORSUBJECTUPPERCASE VARCHAR2(512)       NOT NULL,
   OPERATORSUBJECT      VARCHAR2(512)           NOT NULL,
   OBJECTID             VARCHAR2(128),
   OBJECTTYPE           VARCHAR2(30),
   OPTTYPE              VARCHAR2(30)            NOT NULL,
   OPTTIME              NUMBER(19)              NOT NULL,
   OPTCLIENTIP          VARCHAR2(15),
   OPTRESULT            NUMBER(1)               NOT NULL,
   OPTREMARK            VARCHAR2(1000),
   SIGN_SERVER          VARCHAR2(256),
   CONSTRAINT PK_OPERATIONLOG PRIMARY KEY  (ID)
);
CREATE SEQUENCE LOG_AUTOID INCREMENT BY 1 START WITH 1 MAXVALUE 999999999;
CREATE TABLE OPERATIONLOGARC (
   ID                   NUMBER               	NOT NULL,
   OPERATORSN           VARCHAR2(40),
   OPERATORSUBJECTUPPERCASE VARCHAR2(512)       NOT NULL,
   OPERATORSUBJECT      VARCHAR2(512)         	NOT NULL,
   OBJECTID             VARCHAR2(128),
   OBJECTTYPE           VARCHAR2(30),
   OPTTYPE              VARCHAR2(30)          	NOT NULL,
   OPTTIME              NUMBER(19)              NOT NULL,
   OPTCLIENTIP          VARCHAR2(15),
   OPTRESULT            NUMBER(1)              	NOT NULL,
   OPTREMARK            VARCHAR2(1000),
   SIGN_SERVER          VARCHAR2(256),
   ARCHIVETIME          NUMBER(19)              NOT NULL,
   CONSTRAINT PK_OPERATIONLOGARC PRIMARY KEY  (ID)
);
CREATE TABLE CONSOLEOPTLOG (
   ID                   NUMBER               	NOT NULL,
   OPERATOR             VARCHAR2(30)          	NOT NULL,
   OPTTYPE              VARCHAR2(30)          	NOT NULL,
   OPTTIME              NUMBER(19)              NOT NULL,
   OPTCLIENTIP          VARCHAR2(15),
   OPTRESULT            NUMBER(1)              	NOT NULL,
   OPTREMARK            VARCHAR2(1000),
   SIGN_SERVER          VARCHAR2(256),
   CONSTRAINT PK_CONSOLEOPTLOG PRIMARY KEY  (ID)
);
CREATE SEQUENCE CONSOLEOPTLOG_AUTOID INCREMENT BY 1 START WITH 1 MAXVALUE 999999999;

Insert into SYSTEMCERT (CERTSN,SUBJECT,NOTBEFORE,NOTAFTER,CERTTYPE,CERTSTATUS) values ('4d2b40f5d1e29e02','CN=127.0.0.1,O=EMV,C=CN',NULL,NULL,'COMMUNICATECERT','USING');
Insert into SYSTEMCERT (CERTSN,SUBJECT,NOTBEFORE,NOTAFTER,CERTTYPE,CERTSTATUS) values ('7362e48106a1388a','CN=SuperAdmin,O=EMV,C=CN',NULL,NULL,'SUPERADMINCERT','USING');
COMMIT;